// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Data;

#nullable disable

namespace RpgApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221004011735_MigracaoUsuario")]
    partial class MigracaoUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RpgApi.Models.Arma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Dano")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Armas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dano = 10,
                            Nome = "Ak"
                        },
                        new
                        {
                            Id = 2,
                            Dano = 4,
                            Nome = "Facao"
                        },
                        new
                        {
                            Id = 3,
                            Dano = 5,
                            Nome = "Machado"
                        },
                        new
                        {
                            Id = 4,
                            Dano = 8,
                            Nome = "Espada"
                        },
                        new
                        {
                            Id = 5,
                            Dano = 2,
                            Nome = "Estilingue"
                        },
                        new
                        {
                            Id = 6,
                            Dano = 7,
                            Nome = "Enxada"
                        },
                        new
                        {
                            Id = 7,
                            Dano = 100,
                            Nome = "Cerrinha de Pao"
                        });
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<int>("Defesa")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoPersonagem")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PontosVida")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Personagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = 1,
                            Defesa = 23,
                            Forca = 17,
                            Inteligencia = 33,
                            Nome = "Frodo",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 2,
                            Classe = 1,
                            Defesa = 25,
                            Forca = 15,
                            Inteligencia = 30,
                            Nome = "Sam",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 3,
                            Classe = 3,
                            Defesa = 21,
                            Forca = 18,
                            Inteligencia = 35,
                            Nome = "Galadriel",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 4,
                            Classe = 2,
                            Defesa = 18,
                            Forca = 18,
                            Inteligencia = 37,
                            Nome = "Gandalf",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 5,
                            Classe = 1,
                            Defesa = 17,
                            Forca = 20,
                            Inteligencia = 31,
                            Nome = "Hobbit",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 6,
                            Classe = 3,
                            Defesa = 13,
                            Forca = 21,
                            Inteligencia = 34,
                            Nome = "Celeborn",
                            PontosVida = 100
                        },
                        new
                        {
                            Id = 7,
                            Classe = 2,
                            Defesa = 11,
                            Forca = 25,
                            Inteligencia = 35,
                            Nome = "Radagast",
                            PontosVida = 100
                        });
                });

            modelBuilder.Entity("RpgApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Jogador");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "usuario@gmail.com",
                            Foto = new byte[] { 192, 16, 78, 226, 191, 70, 134, 243, 186, 78, 44, 201, 194, 144, 65, 235, 72, 155, 27, 77, 244, 170, 237, 141, 105, 219, 191, 205, 135, 236, 218, 58, 21, 185, 91, 91, 218, 106, 8, 66, 226, 123, 131, 179, 38, 25, 103, 19, 107, 104, 222, 239, 51, 113, 205, 99, 162, 54, 242, 241, 110, 142, 31, 5 },
                            PasswordHash = new byte[] { 192, 16, 78, 226, 191, 70, 134, 243, 186, 78, 44, 201, 194, 144, 65, 235, 72, 155, 27, 77, 244, 170, 237, 141, 105, 219, 191, 205, 135, 236, 218, 58, 21, 185, 91, 91, 218, 106, 8, 66, 226, 123, 131, 179, 38, 25, 103, 19, 107, 104, 222, 239, 51, 113, 205, 99, 162, 54, 242, 241, 110, 142, 31, 5 },
                            PasswordSalt = new byte[] { 132, 113, 181, 15, 30, 190, 234, 221, 19, 169, 96, 23, 25, 3, 249, 81, 35, 106, 49, 51, 199, 75, 208, 97, 85, 73, 1, 15, 52, 208, 218, 112, 226, 50, 155, 16, 39, 211, 202, 251, 85, 114, 181, 152, 183, 102, 12, 30, 55, 177, 117, 205, 164, 46, 224, 181, 106, 181, 147, 198, 173, 115, 36, 70, 132, 231, 157, 219, 19, 144, 106, 226, 138, 131, 70, 90, 117, 101, 57, 158, 85, 139, 246, 251, 107, 241, 26, 161, 218, 252, 9, 22, 51, 151, 37, 193, 11, 232, 54, 20, 79, 171, 12, 247, 247, 3, 38, 40, 254, 111, 51, 148, 156, 239, 253, 144, 19, 250, 2, 249, 184, 126, 247, 90, 112, 155, 152, 54 },
                            Perfil = "Admin",
                            Username = "UsuarioAdmin"
                        });
                });

            modelBuilder.Entity("RpgApi.Models.Personagem", b =>
                {
                    b.HasOne("RpgApi.Models.Usuario", "Usuario")
                        .WithMany("Personagens")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RpgApi.Models.Usuario", b =>
                {
                    b.Navigation("Personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
